on:
  push:
    paths:
      - 'controllers/**'
      - 'database/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'controllers/**'
      - 'database/**'
      - 'tests/**'
  workflow_dispatch:
